const getImage = (src) => {
    const imgTemp = new Image();
    imgTemp.src = `./assets/${src}`;
    return imgTemp;
}

//loads images on start for example if we want 0 frame, kano, left, fall: images.kano.left.fall[0]

const images = {
    kano: {
        left: {
            fall: [
                getImage('kano/left/fall/0.png'),
                getImage('kano/left/fall/1.png'),
                getImage('kano/left/fall/2.png'),
                getImage('kano/left/fall/3.png'),
                getImage('kano/left/fall/4.png'),
                getImage('kano/left/fall/5.png'),
                getImage('kano/left/fall/6.png'),
            ],
            "high-kick": [
                getImage('kano/left/high-kick/0.png'),
                getImage('kano/left/high-kick/1.png'),
                getImage('kano/left/high-kick/2.png'),
                getImage('kano/left/high-kick/3.png'),
                getImage('kano/left/high-kick/4.png'),
                getImage('kano/left/high-kick/5.png'),
                getImage('kano/left/high-kick/6.png'),
                getImage('kano/left/high-kick/7.png'),
                getImage('kano/left/high-kick/8.png'),
                getImage('kano/left/high-kick/9.png'),
                getImage('kano/left/high-kick/10.png'),
                getImage('kano/left/high-kick/11.png'),

            ],
            "low-punch": [
                getImage('kano/left/low-punch/0.png'),
                getImage('kano/left/low-punch/1.png'),
                getImage('kano/left/low-punch/2.png'),
                getImage('kano/left/low-punch/3.png'),
                getImage('kano/left/low-punch/4.png'),
            ],
            fireball: [
                getImage('kano/left/fireball/0.png'),
                getImage('kano/left/fireball/1.png'),
                getImage('kano/left/fireball/2.png'),
            ],
            jumping: [
                getImage('kano/left/jumping/0.png'),
                getImage('kano/left/jumping/1.png'),
                getImage('kano/left/jumping/2.png'),
                getImage('kano/left/jumping/3.png'),
                getImage('kano/left/jumping/4.png'),
                getImage('kano/left/jumping/5.png'),
            ],
            falling: [
                getImage('kano/left/falling/0.png'),
            ],
            stand: [
                getImage('kano/left/stand/0.png'),
                getImage('kano/left/stand/1.png'),
                getImage('kano/left/stand/2.png'),
                getImage('kano/left/stand/3.png'),
                getImage('kano/left/stand/4.png'),
                getImage('kano/left/stand/5.png'),
                getImage('kano/left/stand/6.png'),
                getImage('kano/left/stand/7.png'),
                getImage('kano/left/stand/8.png'),
            ],
            walking: [
                getImage('kano/left/walking/0.png'),
                getImage('kano/left/walking/1.png'),
                getImage('kano/left/walking/2.png'),
                getImage('kano/left/walking/3.png'),
                getImage('kano/left/walking/4.png'),
                getImage('kano/left/walking/5.png'),
                getImage('kano/left/walking/6.png'),
                getImage('kano/left/walking/7.png'),
                getImage('kano/left/walking/8.png'),
            ],
            "walking-backward": [
                getImage('kano/left/walking-backward/0.png'),
                getImage('kano/left/walking-backward/1.png'),
                getImage('kano/left/walking-backward/2.png'),
                getImage('kano/left/walking-backward/3.png'),
                getImage('kano/left/walking-backward/4.png'),
                getImage('kano/left/walking-backward/5.png'),
                getImage('kano/left/walking-backward/6.png'),
                getImage('kano/left/walking-backward/7.png'),
                getImage('kano/left/walking-backward/8.png'),
            ],
            win: [
                getImage('kano/left/win/0.png'),
                getImage('kano/left/win/1.png'),
                getImage('kano/left/win/2.png'),
                getImage('kano/left/win/3.png'),
                getImage('kano/left/win/4.png'),
                getImage('kano/left/win/5.png'),
                getImage('kano/left/win/6.png'),
                getImage('kano/left/win/7.png'),
                getImage('kano/left/win/8.png'),
                getImage('kano/left/win/9.png'),
            ],
        },
        right: {
            fall: [
                getImage('kano/right/fall/0.png'),
                getImage('kano/right/fall/1.png'),
                getImage('kano/right/fall/2.png'),
                getImage('kano/right/fall/3.png'),
                getImage('kano/right/fall/4.png'),
                getImage('kano/right/fall/5.png'),
                getImage('kano/right/fall/6.png'),
            ],
            "high-kick": [
                getImage('kano/right/high-kick/0.png'),
                getImage('kano/right/high-kick/1.png'),
                getImage('kano/right/high-kick/2.png'),
                getImage('kano/right/high-kick/3.png'),
                getImage('kano/right/high-kick/4.png'),
                getImage('kano/right/high-kick/5.png'),
                getImage('kano/right/high-kick/6.png'),
                getImage('kano/right/high-kick/7.png'),
                getImage('kano/right/high-kick/8.png'),
                getImage('kano/right/high-kick/9.png'),
                getImage('kano/right/high-kick/10.png'),
                getImage('kano/right/high-kick/11.png'),

            ],
            "low-punch": [
                getImage('kano/right/low-punch/0.png'),
                getImage('kano/right/low-punch/1.png'),
                getImage('kano/right/low-punch/2.png'),
                getImage('kano/right/low-punch/3.png'),
                getImage('kano/right/low-punch/4.png'),
            ],
            fireball: [
                getImage('kano/right/fireball/0.png'),
                getImage('kano/right/fireball/1.png'),
                getImage('kano/right/fireball/2.png'),
            ],
            jumping: [
                getImage('kano/right/jumping/0.png'),
                getImage('kano/right/jumping/1.png'),
                getImage('kano/right/jumping/2.png'),
                getImage('kano/right/jumping/3.png'),
                getImage('kano/right/jumping/4.png'),
                getImage('kano/right/jumping/5.png'),
            ],
            falling: [
                getImage('kano/right/falling/0.png'),
            ],
            stand: [
                getImage('kano/right/stand/0.png'),
                getImage('kano/right/stand/1.png'),
                getImage('kano/right/stand/2.png'),
                getImage('kano/right/stand/3.png'),
                getImage('kano/right/stand/4.png'),
                getImage('kano/right/stand/5.png'),
                getImage('kano/right/stand/6.png'),
                getImage('kano/right/stand/7.png'),
                getImage('kano/right/stand/8.png'),
            ],
            walking: [
                getImage('kano/right/walking/0.png'),
                getImage('kano/right/walking/1.png'),
                getImage('kano/right/walking/2.png'),
                getImage('kano/right/walking/3.png'),
                getImage('kano/right/walking/4.png'),
                getImage('kano/right/walking/5.png'),
                getImage('kano/right/walking/6.png'),
                getImage('kano/right/walking/7.png'),
                getImage('kano/right/walking/8.png'),
            ],
            "walking-backward": [
                getImage('kano/right/walking-backward/0.png'),
                getImage('kano/right/walking-backward/1.png'),
                getImage('kano/right/walking-backward/2.png'),
                getImage('kano/right/walking-backward/3.png'),
                getImage('kano/right/walking-backward/4.png'),
                getImage('kano/right/walking-backward/5.png'),
                getImage('kano/right/walking-backward/6.png'),
                getImage('kano/right/walking-backward/7.png'),
                getImage('kano/right/walking-backward/8.png'),
            ],
            win: [
                getImage('kano/right/win/0.png'),
                getImage('kano/right/win/1.png'),
                getImage('kano/right/win/2.png'),
                getImage('kano/right/win/3.png'),
                getImage('kano/right/win/4.png'),
                getImage('kano/right/win/5.png'),
                getImage('kano/right/win/6.png'),
                getImage('kano/right/win/7.png'),
                getImage('kano/right/win/8.png'),
                getImage('kano/right/win/9.png'),
            ],
        }
    },
    subzero: {
        left: {
            fall: [
                getImage('subzero/left/fall/0.png'),
                getImage('subzero/left/fall/1.png'),
                getImage('subzero/left/fall/2.png'),
                getImage('subzero/left/fall/3.png'),
                getImage('subzero/left/fall/4.png'),
                getImage('subzero/left/fall/5.png'),
                getImage('subzero/left/fall/6.png'),
            ],
            "high-kick": [
                getImage('subzero/left/high-kick/0.png'),
                getImage('subzero/left/high-kick/1.png'),
                getImage('subzero/left/high-kick/2.png'),
                getImage('subzero/left/high-kick/3.png'),
                getImage('subzero/left/high-kick/4.png'),
                getImage('subzero/left/high-kick/5.png'),
                getImage('subzero/left/high-kick/6.png'),
                getImage('subzero/left/high-kick/7.png'),
                getImage('subzero/left/high-kick/8.png'),
                getImage('subzero/left/high-kick/9.png'),
                getImage('subzero/left/high-kick/10.png'),
                getImage('subzero/left/high-kick/11.png'),

            ],
            "low-punch": [
                getImage('subzero/left/low-punch/0.png'),
                getImage('subzero/left/low-punch/1.png'),
                getImage('subzero/left/low-punch/2.png'),
                getImage('subzero/left/low-punch/3.png'),
                getImage('subzero/left/low-punch/4.png'),
            ],
            fireball: [
                getImage('subzero/left/fireball/0.png'),
                getImage('subzero/left/fireball/1.png'),
                getImage('subzero/left/fireball/2.png'),
            ],
            jumping: [
                getImage('subzero/left/jumping/0.png'),
                getImage('subzero/left/jumping/1.png'),
                getImage('subzero/left/jumping/2.png'),
                getImage('subzero/left/jumping/3.png'),
                getImage('subzero/left/jumping/4.png'),
                getImage('subzero/left/jumping/5.png'),
            ],
            falling: [
                getImage('subzero/left/falling/0.png'),
            ],
            stand: [
                getImage('subzero/left/stand/0.png'),
                getImage('subzero/left/stand/1.png'),
                getImage('subzero/left/stand/2.png'),
                getImage('subzero/left/stand/3.png'),
                getImage('subzero/left/stand/4.png'),
                getImage('subzero/left/stand/5.png'),
                getImage('subzero/left/stand/6.png'),
                getImage('subzero/left/stand/7.png'),
                getImage('subzero/left/stand/8.png'),
            ],
            walking: [
                getImage('subzero/left/walking/0.png'),
                getImage('subzero/left/walking/1.png'),
                getImage('subzero/left/walking/2.png'),
                getImage('subzero/left/walking/3.png'),
                getImage('subzero/left/walking/4.png'),
                getImage('subzero/left/walking/5.png'),
                getImage('subzero/left/walking/6.png'),
                getImage('subzero/left/walking/7.png'),
                getImage('subzero/left/walking/8.png'),
            ],
            "walking-backward": [
                getImage('subzero/left/walking-backward/0.png'),
                getImage('subzero/left/walking-backward/1.png'),
                getImage('subzero/left/walking-backward/2.png'),
                getImage('subzero/left/walking-backward/3.png'),
                getImage('subzero/left/walking-backward/4.png'),
                getImage('subzero/left/walking-backward/5.png'),
                getImage('subzero/left/walking-backward/6.png'),
                getImage('subzero/left/walking-backward/7.png'),
                getImage('subzero/left/walking-backward/8.png'),
            ],
            win: [
                getImage('subzero/left/win/0.png'),
                getImage('subzero/left/win/1.png'),
                getImage('subzero/left/win/2.png'),
                getImage('subzero/left/win/3.png'),
                getImage('subzero/left/win/4.png'),
                getImage('subzero/left/win/5.png'),
                getImage('subzero/left/win/6.png'),
                getImage('subzero/left/win/7.png'),
                getImage('subzero/left/win/8.png'),
                getImage('subzero/left/win/9.png'),
            ],
        },
        right: {
            fall: [
                getImage('subzero/right/fall/0.png'),
                getImage('subzero/right/fall/1.png'),
                getImage('subzero/right/fall/2.png'),
                getImage('subzero/right/fall/3.png'),
                getImage('subzero/right/fall/4.png'),
                getImage('subzero/right/fall/5.png'),
                getImage('subzero/right/fall/6.png'),
            ],
            "high-kick": [
                getImage('subzero/right/high-kick/0.png'),
                getImage('subzero/right/high-kick/1.png'),
                getImage('subzero/right/high-kick/2.png'),
                getImage('subzero/right/high-kick/3.png'),
                getImage('subzero/right/high-kick/4.png'),
                getImage('subzero/right/high-kick/5.png'),
                getImage('subzero/right/high-kick/6.png'),
                getImage('subzero/right/high-kick/7.png'),
                getImage('subzero/right/high-kick/8.png'),
                getImage('subzero/right/high-kick/9.png'),
                getImage('subzero/right/high-kick/10.png'),
                getImage('subzero/right/high-kick/11.png'),

            ],
            "low-punch": [
                getImage('subzero/right/low-punch/0.png'),
                getImage('subzero/right/low-punch/1.png'),
                getImage('subzero/right/low-punch/2.png'),
                getImage('subzero/right/low-punch/3.png'),
                getImage('subzero/right/low-punch/4.png'),
            ],
            fireball: [
                getImage('subzero/right/fireball/0.png'),
                getImage('subzero/right/fireball/1.png'),
                getImage('subzero/right/fireball/2.png'),
            ],
            jumping: [
                getImage('subzero/right/jumping/0.png'),
                getImage('subzero/right/jumping/1.png'),
                getImage('subzero/right/jumping/2.png'),
                getImage('subzero/right/jumping/3.png'),
                getImage('subzero/right/jumping/4.png'),
                getImage('subzero/right/jumping/5.png'),
            ],
            falling: [
                getImage('subzero/right/falling/0.png'),
            ],
            stand: [
                getImage('subzero/right/stand/0.png'),
                getImage('subzero/right/stand/1.png'),
                getImage('subzero/right/stand/2.png'),
                getImage('subzero/right/stand/3.png'),
                getImage('subzero/right/stand/4.png'),
                getImage('subzero/right/stand/5.png'),
                getImage('subzero/right/stand/6.png'),
                getImage('subzero/right/stand/7.png'),
                getImage('subzero/right/stand/8.png'),
            ],
            walking: [
                getImage('subzero/right/walking/0.png'),
                getImage('subzero/right/walking/1.png'),
                getImage('subzero/right/walking/2.png'),
                getImage('subzero/right/walking/3.png'),
                getImage('subzero/right/walking/4.png'),
                getImage('subzero/right/walking/5.png'),
                getImage('subzero/right/walking/6.png'),
                getImage('subzero/right/walking/7.png'),
                getImage('subzero/right/walking/8.png'),
            ],
            "walking-backward": [
                getImage('subzero/right/walking-backward/0.png'),
                getImage('subzero/right/walking-backward/1.png'),
                getImage('subzero/right/walking-backward/2.png'),
                getImage('subzero/right/walking-backward/3.png'),
                getImage('subzero/right/walking-backward/4.png'),
                getImage('subzero/right/walking-backward/5.png'),
                getImage('subzero/right/walking-backward/6.png'),
                getImage('subzero/right/walking-backward/7.png'),
                getImage('subzero/right/walking-backward/8.png'),
            ],
            win: [
                getImage('subzero/right/win/0.png'),
                getImage('subzero/right/win/1.png'),
                getImage('subzero/right/win/2.png'),
                getImage('subzero/right/win/3.png'),
                getImage('subzero/right/win/4.png'),
                getImage('subzero/right/win/5.png'),
                getImage('subzero/right/win/6.png'),
                getImage('subzero/right/win/7.png'),
                getImage('subzero/right/win/8.png'),
                getImage('subzero/right/win/9.png'),
            ],
        }
    },
    fireball: {
        left: [
            getImage('kano/left/fireball/fireball/0.png'),
            getImage('kano/left/fireball/fireball/1.png'),
            getImage('kano/left/fireball/fireball/2.png'),
            getImage('kano/left/fireball/fireball/3.png'),
            getImage('kano/left/fireball/fireball/4.png'),
        ],
        right: [
            getImage('kano/right/fireball/fireball/0.png'),
            getImage('kano/right/fireball/fireball/1.png'),
            getImage('kano/right/fireball/fireball/2.png'),
            getImage('kano/right/fireball/fireball/3.png'),
            getImage('kano/right/fireball/fireball/4.png'),
        ],
    },
    fireballblue: {
        left: [
            getImage('subzero/left/fireball/fireball/0.png'),
            getImage('subzero/left/fireball/fireball/1.png'),
            getImage('subzero/left/fireball/fireball/2.png'),
            getImage('subzero/left/fireball/fireball/3.png'),
            getImage('subzero/left/fireball/fireball/4.png'),
        ],
        right: [
            getImage('subzero/right/fireball/fireball/0.png'),
            getImage('subzero/right/fireball/fireball/1.png'),
            getImage('subzero/right/fireball/fireball/2.png'),
            getImage('subzero/right/fireball/fireball/3.png'),
            getImage('subzero/right/fireball/fireball/4.png'),
        ],
    }
}